"""Gate: the secrets baseline must have been generated by the scanner CI pins.

WHY THIS EXISTS
---------------
detect-secrets writes its own version into the baseline, and different versions find different
things. The BLOCKING secret gate went red on all four packs on 2026-09-08 because the baselines
had been generated on a developer machine running 1.5.50 while `security.yml` pins 1.5.0: the
runner found five JWT/hex fixtures the local scanner had captured differently, and missed sixteen
"Secret Keyword" hits the local scanner reported. Neither set was wrong; the two scanners simply
disagree, and nothing said the baseline had to come from the pinned one.

There is a second axis and it bit at the same time: the baseline was generated from a Windows
working tree (CRLF) and verified against a Linux checkout (LF), so line-terminal tokens hashed
differently. The regeneration procedure in docs/SECRETS-BASELINE.md pins BOTH — the version and
the checkout — by regenerating inside a fresh clone.

This test only pins the version, because that is the half a file can state about itself.
"""
import io
import json
import os
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent


def test_the_baseline_was_generated_by_the_version_ci_pins():
    wf = ROOT / ".github" / "workflows" / "security.yml"
    assert wf.exists(), "no security workflow: the secret gate is not running at all"
    pinned = re.search(r'"detect-secrets==([0-9][^"]*)"', wf.read_text(encoding="utf-8"))
    assert pinned, "security.yml does not pin detect-secrets to an exact version"

    with io.open(os.path.join(ROOT, ".secrets.baseline"), encoding="utf-8") as fh:
        baseline = json.load(fh)

    assert baseline.get("version") == pinned.group(1), (
        "the committed .secrets.baseline was generated by detect-secrets %s but CI pins %s.\n"
        "Different versions find different secrets, so the BLOCKING gate will fail on findings "
        "that are not new. Regenerate per docs/SECRETS-BASELINE.md (fresh clone + the pinned "
        "version), or change the pin deliberately."
        % (baseline.get("version"), pinned.group(1))
    )
