#!/usr/bin/env python3
"""render.py — turn an agent manifest into the deploy engine's inputs.

Usage: python render.py <manifest.yaml> <build_dir>

Emits into <build_dir>:
  agent.env            shell-sourceable scalars (names, flags, model id)
  tools.tsv            target<TAB>lambda<TAB>handler<TAB>kind<TAB>guardrailed  (manifest order)
  targets/<target>.json  gateway target-configuration (lambdaArn has __ACCOUNT__ placeholder)
  policies.tsv         name<TAB>validation_mode<TAB>cedar_statement (forbids carry __GW_ARN__)
  guardrail-pii.json / guardrail-content.json   guardrail config (empty files if no guardrail)
  users.tsv            name<TAB>password<TAB>in_group(yes/no)

The engine (deploy.sh) sources agent.env and loops over tools.tsv / policies.tsv, substituting
__ACCOUNT__ (known at deploy start) and __GW_ARN__ (known after the gateway is created).
"""
import json
import os
import re
import sys

try:
    import yaml
except ImportError:
    sys.stderr.write("render.py needs PyYAML (pip install pyyaml)\n")
    sys.exit(2)


def sh_quote(v):
    if isinstance(v, bool):
        return "1" if v else "0"
    s = str(v)
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: render.py <manifest.yaml> <build_dir>\n")
        sys.exit(2)
    manifest_path, build = sys.argv[1], sys.argv[2]
    m = yaml.safe_load(open(manifest_path, encoding="utf-8"))
    os.makedirs(os.path.join(build, "targets"), exist_ok=True)

    agent = m["agent"]
    prefix = agent["prefix"]
    region = agent.get("region", "us-east-1")
    ident = m["identity"]
    eng = m["engine"]
    gw = m["gateway"]
    guard = m.get("guardrail")
    controls = m.get("controls", {})
    audit = m.get("audit", {})
    model = m.get("model", {})
    tools = m["tools"]
    policies = m.get("policies", [])

    # map mcp tool name -> gateway target (for policy action ids)
    tool_to_target = {}
    guardrail_lambda = ""
    for t in tools:
        for mt in t.get("mcp_tools", []):
            tool_to_target[mt["name"]] = t["target"]
        if t.get("guardrailed"):
            guardrail_lambda = t["lambda"]

    # ---- agent.env ----
    env = []
    env.append("# generated by render.py — do not edit")
    env.append("PREFIX=%s" % sh_quote(prefix))
    env.append("SLUG=%s" % sh_quote(agent["slug"]))
    env.append("REGION=%s" % sh_quote(region))
    env.append("ENGINE_NAME=%s" % sh_quote(eng["name"]))
    env.append("ENGINE_DESC=%s" % sh_quote(eng.get("description", eng["name"])))
    env.append("GATEWAY_NAME=%s" % sh_quote(gw["name"]))
    env.append("GATEWAY_DESC=%s" % sh_quote(gw.get("description", gw["name"])))
    env.append("SSM_PARAM=%s" % sh_quote(gw["ssm_discovery_param"]))
    env.append("POOL_NAME=%s" % sh_quote(ident["pool_name"]))
    env.append("CLIENT_NAME=%s" % sh_quote(ident["client_name"]))
    env.append("REVIEWER_GROUP=%s" % sh_quote(ident["reviewer_group"]))
    env.append("AUDIT_TABLE=%s" % sh_quote("%s-audit" % prefix))
    env.append("PENDING_TABLE=%s" % sh_quote("%s-pending-approvals" % prefix))
    env.append("WORM_BUCKET_BASE=%s" % sh_quote("%s-audit-worm" % prefix))
    env.append("OBJECT_LOCK_MODE=%s" % sh_quote(audit.get("object_lock_mode", "GOVERNANCE")))
    env.append("RETENTION_DAYS=%s" % sh_quote(audit.get("retention_days", 1)))
    env.append("DRAFT_MODEL_ID=%s" % sh_quote(model.get("draft_model_id", "")))
    env.append("GUARDRAIL_NAME=%s" % sh_quote(guard["name"] if guard else ""))
    env.append("GUARDRAIL_DESC=%s" % sh_quote(guard.get("description", "") if guard else ""))
    env.append("GUARDRAIL_LAMBDA=%s" % sh_quote(guardrail_lambda))
    env.append("CTRL_MASKING=%s" % sh_quote(bool(controls.get("fail_closed_masking"))))
    env.append("CTRL_WORM=%s" % sh_quote(bool(controls.get("worm_audit"))))
    env.append("CTRL_SIGNOFF=%s" % sh_quote(bool(controls.get("human_signoff_gate"))))
    env.append("SM_NAME=%s" % sh_quote("%s-signoff" % prefix))
    # ---- runtime config (consumed by lib/runtime helpers + agent.py via env) ----
    runtime_cfg = m.get("runtime", {})
    slug_id = re.sub(r"[^a-z0-9]+", "_", agent["slug"].lower()).strip("_")
    runtime_name = runtime_cfg.get("name") or (slug_id + "_agent")
    runtime_model = model.get("runtime_model_id") or model.get("draft_model_id", "")
    wf = m.get("workflow", {})
    consequential = wf.get("consequential_action", "")
    steps = wf.get("steps", [])
    step_txt = " ".join("%d) %s" % (i + 1, s) for i, s in enumerate(steps))
    prompt = ("You are a %s agent running under strict governance on Amazon Bedrock AgentCore. "
              "Your tools are exposed via a governed gateway; every call is authorized by policy "
              "against the human identity you act for. Follow this workflow: %s "
              % (agent.get("title", agent["slug"]), step_txt))
    if consequential:
        prompt += "NEVER call %s directly - it is forbidden by policy; the human sign-off gate owns it. " % consequential
    prompt += ("If any tool is denied by policy, STOP and report exactly which control blocked you. "
               "End with a short summary of what you did and the sign-off status.")
    prompt = prompt.replace('"', "'")  # value is passed via --env; keep it double-quote-free
    env.append("RUNTIME_NAME=%s" % sh_quote(runtime_name))
    env.append("RUNTIME_MODEL_ID=%s" % sh_quote(runtime_model))
    env.append("WORKFLOW_PROMPT=%s" % sh_quote(prompt))
    open(os.path.join(build, "agent.env"), "w", encoding="utf-8", newline="\n").write("\n".join(env) + "\n")

    # ---- tools.tsv + target json ----
    lines = []
    for t in tools:
        lines.append("\t".join([t["target"], t["lambda"], t["handler"], t.get("kind", "domain"),
                                "1" if t.get("guardrailed") else "0"]))
        inline = []
        for mt in t["mcp_tools"]:
            props = {}
            for pname, pspec in (mt.get("input") or {}).items():
                props[pname] = {"type": pspec["type"], "description": pspec.get("description", "")}
            inline.append({
                "name": mt["name"],
                "description": mt.get("description", ""),
                "inputSchema": {"type": "object", "properties": props, "required": mt.get("required", [])},
            })
        target_cfg = {"mcp": {"lambda": {
            "lambdaArn": "arn:aws:lambda:%s:__ACCOUNT__:function:%s" % (region, t["lambda"]),
            "toolSchema": {"inlinePayload": inline},
        }}}
        with open(os.path.join(build, "targets", t["target"] + ".json"), "w", encoding="utf-8", newline="\n") as f:
            json.dump(target_cfg, f)
    open(os.path.join(build, "tools.tsv"), "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")

    # ---- policies.tsv (cedar statements; forbids carry __GW_ARN__) ----
    def action_id(tool_name):
        tgt = tool_to_target.get(tool_name)
        if not tgt:
            raise SystemExit("policy references unknown tool '%s' (not in any target's mcp_tools)" % tool_name)
        return "%s___%s" % (tgt, tool_name)

    prows = []
    for p in policies:
        kind = p["kind"]
        if kind == "permit":
            grp = p.get("role_group", ident["reviewer_group"])
            stmt = ('permit(principal, action, resource is AgentCore::Gateway) when { '
                    'principal.hasTag("cognito:groups") && '
                    'principal.getTag("cognito:groups") like "*%s*" };' % grp)
            mode = p.get("validation_mode", "FAIL_ON_ANY_FINDINGS")
        elif kind == "forbid":
            aid = action_id(p["action"])
            base = ('forbid(principal, action == AgentCore::Action::"%s", '
                    'resource == AgentCore::Gateway::"__GW_ARN__")' % aid)
            if p.get("unless_deidentified"):
                stmt = base + " unless { context.input.deidentified == true };"
            else:
                stmt = base + ";"
            mode = p.get("validation_mode", "IGNORE_ALL_FINDINGS")
        else:
            raise SystemExit("unknown policy kind '%s'" % kind)
        # Prefix the policy name with the agent prefix. AgentCore Policy names are unique per
        # account/region, and template agents share logical names (mask_before_assess, no_self_commit,
        # ...). Prefixing (e.g. ben_mask_before_assess) lets multiple agents coexist in one account.
        # Policy names must match ^[A-Za-z][A-Za-z0-9_]*$ — underscore separator (no hyphen).
        prows.append("\t".join(["%s_%s" % (prefix, p["name"]), mode, stmt]))
    open(os.path.join(build, "policies.tsv"), "w", encoding="utf-8", newline="\n").write("\n".join(prows) + "\n")

    # ---- guardrail config ----
    if guard:
        pii = [{"type": x, "action": "ANONYMIZE"} for x in guard.get("pii_anonymize", [])]
        open(os.path.join(build, "guardrail-pii.json"), "w", encoding="utf-8", newline="\n").write(
            json.dumps({"piiEntitiesConfig": pii}))
        pa = guard.get("prompt_attack", "HIGH")
        open(os.path.join(build, "guardrail-content.json"), "w", encoding="utf-8", newline="\n").write(
            json.dumps({"filtersConfig": [{"type": "PROMPT_ATTACK", "inputStrength": pa, "outputStrength": "NONE"}]}))

    # ---- users.tsv ----
    urows = []
    for u in ident.get("users", []):
        urows.append("\t".join([u["name"], u["password"], "yes" if u.get("in_group") else "no"]))
    open(os.path.join(build, "users.tsv"), "w", encoding="utf-8", newline="\n").write("\n".join(urows) + "\n")

    print("rendered %s -> %s (%d tools, %d policies)" % (agent["slug"], build, len(tools), len(policies)))


if __name__ == "__main__":
    main()
