#!/usr/bin/env python3
"""Regenerate lib/core.lock from the current governance core (P0-9). Run this ONLY when deliberately
changing the shared core; it re-hashes every core file and writes the lock with a version. The same
regenerated core + lock must then be synced to every vertical so all four stay byte-identical.

Usage:
  python lib/regen_core_lock.py                 # keep the version in lib/CORE_VERSION, re-lock
  python lib/regen_core_lock.py --set 1.2.0     # set an explicit version
  python lib/regen_core_lock.py --bump patch    # bump patch|minor|major from CORE_VERSION
Stdlib only."""
import os
import sys

LIB = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, LIB)
import verify_core as vc  # reuse discover()/_sha256()

CORE_VERSION = os.path.join(LIB, "CORE_VERSION")


def read_version():
    with open(CORE_VERSION, encoding="utf-8") as fh:
        return fh.read().strip()


def bump(ver, part):
    a, b, c = (list(map(int, ver.split("."))) + [0, 0, 0])[:3]
    if part == "major": a, b, c = a + 1, 0, 0
    elif part == "minor": b, c = b + 1, 0
    else: c += 1
    return "%d.%d.%d" % (a, b, c)


def main(argv):
    ver = read_version()
    if "--set" in argv:
        ver = argv[argv.index("--set") + 1]
    elif "--bump" in argv:
        ver = bump(ver, argv[argv.index("--bump") + 1])
    files = vc.discover()  # {rel: abspath}, excludes the lock
    # CORE_VERSION must reflect the version we lock
    with open(CORE_VERSION, "w", encoding="utf-8") as fh:
        fh.write(ver + "\n")
    rows = []
    for rel in sorted(files):
        rows.append("%s  %s" % (vc._sha256(files[rel]), rel))
    import hashlib
    tree = hashlib.sha256(("\n".join(rows)).encode("utf-8")).hexdigest()
    lock = os.path.join(LIB, "core.lock")
    with open(lock, "w", encoding="utf-8") as fh:
        fh.write("# governed governance core — integrity lock (P0-9). Generated by regen_core_lock.py; do not hand-edit.\n")
        fh.write("# Every vertical carries this identical core, pinned to this version. CI runs lib/verify_core.py\n")
        fh.write("# and fails the build on any drift. Change the core -> re-run regen_core_lock.py -> sync to all verticals.\n")
        fh.write("version: %s\n" % ver)
        fh.write("files: %d\n" % len(rows))
        fh.write("tree_sha256: %s\n" % tree)
        for r in rows:
            fh.write(r + "\n")
    print("wrote %s: version %s, %d files, tree_sha256 %s" % (lock, ver, len(rows), tree))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
